2024-06-03T03:42:38 {"cpu": 0.15185546875, "cpu_total": 4, "cpu_usage": 0.0379638671875, "memory": 2098.0, "memory_total": 4957.0, "memory_usage": 0.42323986282025416, "pipeline_run_id": 14, "pipeline_schedule_id": 5, "pipeline_uuid": "pipe_zebrinha_azul", "hostname": "b8c69530f242", "level": "INFO", "message": "Pipeline pipe_zebrinha_azul for run 14 in schedule 5 is alive.", "timestamp": 1717386158.984321, "uuid": "2739874b15ea4694943ca3d2c0e39bde"}
2024-06-03T03:42:39 {"cpu": 0.15185546875, "cpu_total": 4, "cpu_usage": 0.0379638671875, "memory": 2172.0, "memory_total": 4957.0, "memory_usage": 0.43816824692354245, "pipeline_run_id": 14, "pipeline_schedule_id": 5, "pipeline_uuid": "pipe_zebrinha_azul", "hostname": "b8c69530f242", "level": "INFO", "message": "Pipeline pipe_zebrinha_azul for run 14 in schedule 5 is alive.", "timestamp": 1717386159.731362, "uuid": "b226e67ebc0447c58b22f80ace587cab"}
2024-06-03T03:42:39 {"block_run_id": 37, "block_uuid": "load_data_from_destinations_api", "pipeline_run_id": 14, "pipeline_schedule_id": 5, "pipeline_uuid": "pipe_zebrinha_azul", "hostname": "b8c69530f242", "level": "INFO", "message": "Execute PipelineRun 14, BlockRun 37: pipeline pipe_zebrinha_azul block load_data_from_destinations_api", "timestamp": 1717386159.895289, "uuid": "94ff3c2e15fb4a3e8f62913ada3be2a8"}
2024-06-03T03:42:39 {"block_run_id": 40, "block_uuid": "trigger_data_loader_weather", "pipeline_run_id": 14, "pipeline_schedule_id": 5, "pipeline_uuid": "pipe_zebrinha_azul", "hostname": "b8c69530f242", "level": "INFO", "message": "Execute PipelineRun 14, BlockRun 40: pipeline pipe_zebrinha_azul block trigger_data_loader_weather", "timestamp": 1717386159.926456, "uuid": "30e0be2f0fd24f81b6694a92182dbe8f"}
2024-06-03T03:42:40 {"block_run_id": 40, "block_uuid": "trigger_data_loader_weather", "pipeline_run_id": 14, "pipeline_schedule_id": 5, "pipeline_uuid": "pipe_zebrinha_azul", "hostname": "b8c69530f242", "level": "INFO", "message": "BlockRun 40 (block_uuid: trigger_data_loader_weather) completes.", "timestamp": 1717386160.355465, "uuid": "d5605d71978e43228d4da7c3d232ab47"}
2024-06-03T03:42:49 {"cpu": 0.16650390625, "cpu_total": 4, "cpu_usage": 0.0416259765625, "memory": 2156.0, "memory_total": 4957.0, "memory_usage": 0.43494048819850717, "pipeline_run_id": 14, "pipeline_schedule_id": 5, "pipeline_uuid": "pipe_zebrinha_azul", "hostname": "b8c69530f242", "level": "INFO", "message": "Pipeline pipe_zebrinha_azul for run 14 in schedule 5 is alive.", "timestamp": 1717386169.253975, "uuid": "2395f631b573449ab90f1e1c10300dc6"}
2024-06-03T03:42:58 {"cpu": 0.17041015625, "cpu_total": 4, "cpu_usage": 0.0426025390625, "memory": 2159.0, "memory_total": 4957.0, "memory_usage": 0.4355456929594513, "pipeline_run_id": 14, "pipeline_schedule_id": 5, "pipeline_uuid": "pipe_zebrinha_azul", "hostname": "b8c69530f242", "level": "INFO", "message": "Pipeline pipe_zebrinha_azul for run 14 in schedule 5 is alive.", "timestamp": 1717386178.506015, "uuid": "336fe27e9bb3426ea26fc2107ac3074a"}
2024-06-03T03:43:08 {"cpu": 0.17431640625, "cpu_total": 4, "cpu_usage": 0.0435791015625, "memory": 2166.0, "memory_total": 4957.0, "memory_usage": 0.4369578374016542, "pipeline_run_id": 14, "pipeline_schedule_id": 5, "pipeline_uuid": "pipe_zebrinha_azul", "hostname": "b8c69530f242", "level": "INFO", "message": "Pipeline pipe_zebrinha_azul for run 14 in schedule 5 is alive.", "timestamp": 1717386188.546735, "uuid": "c59d943c8fe1458d98c3c4f25623de47"}
2024-06-03T03:43:16 {"block_run_id": 37, "block_uuid": "load_data_from_destinations_api", "pipeline_run_id": 14, "pipeline_schedule_id": 5, "pipeline_uuid": "pipe_zebrinha_azul", "hostname": "b8c69530f242", "level": "INFO", "message": "BlockRun 37 (block_uuid: load_data_from_destinations_api) completes.", "timestamp": 1717386196.243415, "uuid": "5b665f509b9543bfa07a61d34cf5d2e2"}
2024-06-03T03:43:18 {"cpu": 0.17236328125, "cpu_total": 4, "cpu_usage": 0.0430908203125, "memory": 2100.0, "memory_total": 4957.0, "memory_usage": 0.4236433326608836, "pipeline_run_id": 14, "pipeline_schedule_id": 5, "pipeline_uuid": "pipe_zebrinha_azul", "hostname": "b8c69530f242", "level": "INFO", "message": "Pipeline pipe_zebrinha_azul for run 14 in schedule 5 is alive.", "timestamp": 1717386198.745266, "uuid": "dbed3cf2fb0b4430bdf1858cbe7673f0"}
2024-06-03T03:43:18 {"block_run_id": 38, "block_uuid": "clean_data_from_destinations_api", "pipeline_run_id": 14, "pipeline_schedule_id": 5, "pipeline_uuid": "pipe_zebrinha_azul", "hostname": "b8c69530f242", "level": "INFO", "message": "Execute PipelineRun 14, BlockRun 38: pipeline pipe_zebrinha_azul block clean_data_from_destinations_api", "timestamp": 1717386198.97321, "uuid": "4f56173111894ebab6e4042b34ff778b"}
2024-06-03T03:43:20 {"block_run_id": 38, "block_uuid": "clean_data_from_destinations_api", "pipeline_run_id": 14, "pipeline_schedule_id": 5, "pipeline_uuid": "pipe_zebrinha_azul", "hostname": "b8c69530f242", "level": "EXCEPTION", "message": "BlockRun 38 (block_uuid: clean_data_from_destinations_api) failed.", "timestamp": 1717386200.283306, "uuid": "cf381724d1de467a8fc45c5689708e24", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1672, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1649, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1551, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1891, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2054, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2150, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 29, in transform\n  File \"<string>\", line 29, in <dictcomp>\nKeyError: 'place_id'\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 164, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 777, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 101, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 53, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1671, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 320, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 623, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 28, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1177, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 682, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 452, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["'place_id'"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1154, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1672, in execute_sync
    return __execute()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1649, in __execute
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1551, in __execute
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1891, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2054, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2150, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 29, in transform
  File "<string>", line 29, in <dictcomp>
KeyError: 'place_id'
2024-06-03T03:43:29 {"cpu": 0.17041015625, "cpu_total": 4, "cpu_usage": 0.0426025390625, "memory": 2100.0, "memory_total": 4957.0, "memory_usage": 0.4236433326608836, "pipeline_run_id": 14, "pipeline_schedule_id": 5, "pipeline_uuid": "pipe_zebrinha_azul", "hostname": "b8c69530f242", "level": "INFO", "message": "Pipeline pipe_zebrinha_azul for run 14 in schedule 5 is alive.", "timestamp": 1717386209.045233, "uuid": "d4d784a625354c6bbd332f7f0a73df6f"}
