2024-06-01T03:08:32 {"cpu": 0.56103515625, "cpu_total": 4, "cpu_usage": 0.1402587890625, "memory": 1539.0, "memory_total": 4957.0, "memory_usage": 0.3104700423643333, "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "pipe_zebrinha_azul", "hostname": "8609f67b5852", "level": "INFO", "message": "Pipeline pipe_zebrinha_azul for run 3 in schedule 1 is alive.", "timestamp": 1717211312.653012, "uuid": "68b6f0553d154882b96f272efd6c84a3"}
2024-06-01T03:08:32 {"cpu": 0.56103515625, "cpu_total": 4, "cpu_usage": 0.1402587890625, "memory": 1579.0, "memory_total": 4957.0, "memory_usage": 0.3185394391769215, "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "pipe_zebrinha_azul", "hostname": "8609f67b5852", "level": "INFO", "message": "Pipeline pipe_zebrinha_azul for run 3 in schedule 1 is alive.", "timestamp": 1717211312.90263, "uuid": "ab30aad801f942aba87244d2a2070f3b"}
2024-06-01T03:08:32 {"block_run_id": 5, "block_uuid": "load_data_from_destinations_api", "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "pipe_zebrinha_azul", "hostname": "8609f67b5852", "level": "INFO", "message": "Execute PipelineRun 3, BlockRun 5: pipeline pipe_zebrinha_azul block load_data_from_destinations_api", "timestamp": 1717211312.983929, "uuid": "25360d72031c4035a000dcca7dd2868b"}
2024-06-01T03:08:39 {"block_run_id": 5, "block_uuid": "load_data_from_destinations_api", "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "pipe_zebrinha_azul", "hostname": "8609f67b5852", "level": "INFO", "message": "BlockRun 5 (block_uuid: load_data_from_destinations_api) completes.", "timestamp": 1717211319.959337, "uuid": "b759317f18a743a19daf1b748b930249"}
2024-06-01T03:08:43 {"cpu": 0.58349609375, "cpu_total": 4, "cpu_usage": 0.1458740234375, "memory": 1575.0, "memory_total": 4957.0, "memory_usage": 0.3177324994956627, "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "pipe_zebrinha_azul", "hostname": "8609f67b5852", "level": "INFO", "message": "Pipeline pipe_zebrinha_azul for run 3 in schedule 1 is alive.", "timestamp": 1717211323.102562, "uuid": "5e7eab50021b4d5ea17bd75dfa57882c"}
2024-06-01T03:08:52 {"cpu": 0.580078125, "cpu_total": 4, "cpu_usage": 0.14501953125, "memory": 1549.0, "memory_total": 4957.0, "memory_usage": 0.31248739156748034, "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "pipe_zebrinha_azul", "hostname": "8609f67b5852", "level": "INFO", "message": "Pipeline pipe_zebrinha_azul for run 3 in schedule 1 is alive.", "timestamp": 1717211332.30333, "uuid": "56442e28872f4992b2df2cbc401e829b"}
2024-06-01T03:08:52 {"block_run_id": 6, "block_uuid": "clean_data_from_destinations_api", "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "pipe_zebrinha_azul", "hostname": "8609f67b5852", "level": "INFO", "message": "Execute PipelineRun 3, BlockRun 6: pipeline pipe_zebrinha_azul block clean_data_from_destinations_api", "timestamp": 1717211332.814839, "uuid": "1765da3cb94945bcad85aa4d6c1fc7f7"}
2024-06-01T03:08:53 {"block_run_id": 6, "block_uuid": "clean_data_from_destinations_api", "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "pipe_zebrinha_azul", "hostname": "8609f67b5852", "level": "EXCEPTION", "message": "BlockRun 6 (block_uuid: clean_data_from_destinations_api) failed.", "timestamp": 1717211333.871906, "uuid": "86423c25b7a141458460864423849ebf", "error": ["Traceback (most recent call last):\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 647, in execute\n    result = __execute_with_retry()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 54, in retry_func\n    raise e\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py\", line 38, in retry_func\n    return func(*args, **kwargs)\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 621, in __execute_with_retry\n    return self._execute(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 1154, in _execute\n    result = self.block.execute_sync(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1672, in execute_sync\n    return __execute()\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1649, in __execute\n    raise err\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1551, in __execute\n    output = self.execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 1891, in execute_block\n    outputs = self._execute_block(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2054, in _execute_block\n    outputs = self.execute_block_function(\n  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py\", line 2150, in execute_block_function\n    output = block_function_updated(*input_vars, **global_vars)\n  File \"<string>\", line 13, in transform\nTypeError: string indices must be integers\n"], "error_stack": [["  File \"/usr/local/bin/mage\", line 8, in <module>\n    sys.exit(app())\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 311, in __call__\n    return get_command(self)(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1130, in __call__\n    return self.main(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 778, in main\n    return _main(\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/core.py\", line 216, in _main\n    rv = self.invoke(ctx)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1657, in invoke\n    return _process_result(sub_ctx.command.invoke(sub_ctx))\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 1404, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n", "  File \"/usr/local/lib/python3.10/site-packages/click/core.py\", line 760, in invoke\n    return __callback(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/typer/main.py\", line 683, in wrapper\n    return callback(**use_params)  # type: ignore\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/cli/main.py\", line 164, in start\n    start_server(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/server.py\", line 777, in start_server\n    scheduler_manager.start_scheduler()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 101, in start_scheduler\n    proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/server/scheduler_manager.py\", line 53, in run_scheduler\n    LoopTimeTrigger().start()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/loop_time_trigger.py\", line 14, in start\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/triggers/time_trigger.py\", line 11, in run\n    schedule_all()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1671, in schedule_all\n    PipelineScheduler(r).schedule()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 320, in schedule\n    self.__schedule_blocks(block_runs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 623, in __schedule_blocks\n    job_manager.add_job(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/job_manager.py\", line 28, in add_job\n    self.queue.enqueue(job_id, target, *args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 121, in enqueue\n    self.start_worker_pool()\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 198, in start_worker_pool\n    self.worker_pool_proc.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 108, in run\n    self._target(*self._args, **self._kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 351, in poll_job_and_execute\n    worker.start()\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 121, in start\n    self._popen = self._Popen(self)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 224, in _Popen\n    return _default_context.get_context().Process._Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/context.py\", line 281, in _Popen\n    return Popen(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 19, in __init__\n    self._launch(process_obj)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/popen_fork.py\", line 71, in _launch\n    code = process_obj._bootstrap(parent_sentinel=child_r)\n", "  File \"/usr/local/lib/python3.10/multiprocessing/process.py\", line 314, in _bootstrap\n    self.run()\n", "  File \"/usr/local/lib/python3.10/site-packages/newrelic/api/background_task.py\", line 117, in wrapper\n    return wrapped(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/queue/process_queue.py\", line 315, in run\n    start_session_and_run(args[1], *args[2], **args[3])\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/process.py\", line 15, in start_session_and_run\n    results = target(*args)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 1177, in run_block\n    return ExecutorFactory.get_block_executor(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py\", line 682, in execute\n    on_failure(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/db/__init__.py\", line 158, in func_with_rollback\n    return func(*args, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/orchestration/pipeline_scheduler_original.py\", line 452, in on_block_failure\n    self.logger.exception(\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 30, in exception\n    self.__send_message('exception', message, **kwargs)\n", "  File \"/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/logging/logger.py\", line 65, in __send_message\n    data['error_stack'] = traceback.format_stack(),\n"]], "error_stacktrace": ["string indices must be integers"]}
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 647, in execute
    result = __execute_with_retry()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 54, in retry_func
    raise e
  File "/usr/local/lib/python3.10/site-packages/mage_ai/shared/retry.py", line 38, in retry_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 621, in __execute_with_retry
    return self._execute(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/executors/block_executor.py", line 1154, in _execute
    result = self.block.execute_sync(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1672, in execute_sync
    return __execute()
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1649, in __execute
    raise err
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1551, in __execute
    output = self.execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 1891, in execute_block
    outputs = self._execute_block(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2054, in _execute_block
    outputs = self.execute_block_function(
  File "/usr/local/lib/python3.10/site-packages/mage_ai/data_preparation/models/block/__init__.py", line 2150, in execute_block_function
    output = block_function_updated(*input_vars, **global_vars)
  File "<string>", line 13, in transform
TypeError: string indices must be integers
2024-06-01T03:09:02 {"cpu": 0.59521484375, "cpu_total": 4, "cpu_usage": 0.1488037109375, "memory": 1610.0, "memory_total": 4957.0, "memory_usage": 0.3247932217066774, "pipeline_run_id": 3, "pipeline_schedule_id": 1, "pipeline_uuid": "pipe_zebrinha_azul", "hostname": "8609f67b5852", "level": "INFO", "message": "Pipeline pipe_zebrinha_azul for run 3 in schedule 1 is alive.", "timestamp": 1717211342.915261, "uuid": "b54ce1e0ff694f04a210dcfc3765514d"}
